# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Add_participant.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_participant(object):
    def setupUi(self, Add_participant):
        Add_participant.setObjectName("Add_participant")
        Add_participant.resize(608, 376)
        self.gridLayout = QtWidgets.QGridLayout(Add_participant)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Add_participant)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 3, 1, 1)
        self.lineEdit_number_phone_participant = QtWidgets.QLineEdit(Add_participant)
        self.lineEdit_number_phone_participant.setObjectName("lineEdit_number_phone_participant")
        self.gridLayout.addWidget(self.lineEdit_number_phone_participant, 2, 0, 1, 1)
        self.label_add_participant_event = QtWidgets.QLabel(Add_participant)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_add_participant_event.setFont(font)
        self.label_add_participant_event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_participant_event.setObjectName("label_add_participant_event")
        self.gridLayout.addWidget(self.label_add_participant_event, 1, 0, 1, 4)
        self.treeWidget = QtWidgets.QTreeWidget(Add_participant)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 4, 0, 1, 4)
        self.pushButton_find_participant = QtWidgets.QPushButton(Add_participant)
        self.pushButton_find_participant.setObjectName("pushButton_find_participant")
        self.gridLayout.addWidget(self.pushButton_find_participant, 2, 2, 1, 1)
        self.lineEdit_second_name_participant = QtWidgets.QLineEdit(Add_participant)
        self.lineEdit_second_name_participant.setObjectName("lineEdit_second_name_participant")
        self.gridLayout.addWidget(self.lineEdit_second_name_participant, 2, 1, 1, 1)
        self.label_username_login_role = QtWidgets.QLabel(Add_participant)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 0, 2, 1, 2)
        self.pushButton_add_selected_participant = QtWidgets.QPushButton(Add_participant)
        self.pushButton_add_selected_participant.setObjectName("pushButton_add_selected_participant")
        self.gridLayout.addWidget(self.pushButton_add_selected_participant, 5, 0, 1, 1)

        self.retranslateUi(Add_participant)
        self.buttonBox.accepted.connect(Add_participant.accept) # type: ignore
        self.buttonBox.rejected.connect(Add_participant.reject) # type: ignore
        self.pushButton_add_selected_participant.clicked.connect(Add_participant.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Add_participant)

    def retranslateUi(self, Add_participant):
        _translate = QtCore.QCoreApplication.translate
        Add_participant.setWindowTitle(_translate("Add_participant", "Логистик"))
        self.lineEdit_number_phone_participant.setPlaceholderText(_translate("Add_participant", "Номер телефона..."))
        self.label_add_participant_event.setText(_translate("Add_participant", "Добавить участника мероприятия"))
        self.treeWidget.headerItem().setText(0, _translate("Add_participant", "Телефон"))
        self.treeWidget.headerItem().setText(1, _translate("Add_participant", "Фамилия"))
        self.treeWidget.headerItem().setText(2, _translate("Add_participant", "Имя"))
        self.treeWidget.headerItem().setText(3, _translate("Add_participant", "Отчество"))
        self.pushButton_find_participant.setText(_translate("Add_participant", "Найти"))
        self.lineEdit_second_name_participant.setPlaceholderText(_translate("Add_participant", "Фамилия..."))
        self.label_username_login_role.setText(_translate("Add_participant", "username_login_role"))
        self.pushButton_add_selected_participant.setText(_translate("Add_participant", "Добавить выбранного"))
