from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_List_organization(object):
    def setupUi(self, List_organization):
        List_organization.setObjectName("List_organization")
        List_organization.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(List_organization)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_edit_organization = QtWidgets.QPushButton(List_organization)
        self.pushButton_edit_organization.setObjectName("pushButton_edit_organization")
        self.gridLayout.addWidget(self.pushButton_edit_organization, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.pushButton_add_organization = QtWidgets.QPushButton(List_organization)
        self.pushButton_add_organization.setObjectName("pushButton_add_organization")
        self.gridLayout.addWidget(self.pushButton_add_organization, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(List_organization)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 3, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(List_organization)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 2, 0, 1, 4)
        self.pushButton_delete_organization = QtWidgets.QPushButton(List_organization)
        self.pushButton_delete_organization.setObjectName("pushButton_delete_organization")
        self.gridLayout.addWidget(self.pushButton_delete_organization, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(List_organization)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 4)
        self.label_username_login_role = QtWidgets.QLabel(List_organization)
        self.label_username_login_role.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_username_login_role.setObjectName("label_username_login_role")
        self.gridLayout.addWidget(self.label_username_login_role, 0, 3, 1, 1)

        self.retranslateUi(List_organization)
        self.buttonBox.accepted.connect(List_organization.accept)
        self.buttonBox.rejected.connect(List_organization.reject)
        QtCore.QMetaObject.connectSlotsByName(List_organization)

    def retranslateUi(self, List_organization):
        _translate = QtCore.QCoreApplication.translate
        List_organization.setWindowTitle(_translate("List_organization", " Логистик"))
        self.pushButton_edit_organization.setText(_translate("List_organization", "Редактировать"))
        self.pushButton_add_organization.setText(_translate("List_organization", "Добавить"))
        self.pushButton_delete_organization.setText(_translate("List_organization", "Удалить"))
        self.label.setText(_translate("List_organization", "Список организаций"))
        self.label_username_login_role.setText(_translate("List_organization", "username_login_role"))
